In [ ]:
import pandas as pd
from os import path

df = pd.read_csv(path.join(root_path, 'titanic.csv'), sep=',')
df.head()

In [ ]:
df1 = pd.read_excel(path.join(root_path, 'titanic.xlsx'), sheet_name=1)
# df1 = pd.read_excel(path.join(root_path, 'titanic.xlsx'), sheet_name="pClass1")
df1.head()

In [ ]:
df2 = pd.read_json(path.join(root_path, 'titanic.json'))
df2.read()

In [3]:
import pandas as pd
import numpy as np

df3 = pd.DataFrame({
    'A' : ["df3_A0", "df3_A1", "df3_A2"],
    'B' : ["df3_B0", "df3_B1", "df3_B2"],
    'C' : ["df3_C0", "df3_C1", "df3_C2"]
})

df4 = pd.DataFrame({
    'E' : ["df4_E4", "df4_E3", "df4_E2"],
    'D' : ["df4_D4", "df4_D3", "df4_D2"],
    'C' : ["df4_C4", "df4_C3", "df4_C2"]
}, index = [4, 3, 2])

df5 = pd.DataFrame({
    'F' : [np.nan, np.nan, np.nan],
    'G' : [np.nan, "df5_G6", "df5_G7", ],
    'C' : ["df5_C6", "df5_C6", "df5_C7"]
}, index=[5, 6, 7])

result = pd.concat([df3, df4], axis=0, sort=False)
result

        A       B       C       E       D
0  df3_A0  df3_B0  df3_C0     NaN     NaN
1  df3_A1  df3_B1  df3_C1     NaN     NaN
2  df3_A2  df3_B2  df3_C2     NaN     NaN
4     NaN     NaN  df4_C4  df4_E4  df4_D4
3     NaN     NaN  df4_C3  df4_E3  df4_D3
2     NaN     NaN  df4_C2  df4_E2  df4_D2

In [12]:
result = pd.concat([df3, df4], axis=1, sort=True)
result

        A       B       C       E       D       C
0  df3_A0  df3_B0  df3_C0     NaN     NaN     NaN
1  df3_A1  df3_B1  df3_C1     NaN     NaN     NaN
2  df3_A2  df3_B2  df3_C2  df4_E2  df4_D2  df4_C2
3     NaN     NaN     NaN  df4_E3  df4_D3  df4_C3
4     NaN     NaN     NaN  df4_E4  df4_D4  df4_C4

In [5]:
def get_df():
  return pd.concat([df3, df4, df5], sort=True, ignore_index=True)

df = get_df()
df = df.drop(index=[1, 3, 4, 8])
# df = df.drop(columns=['C', 'D', 'E', 'G'])
df

        A       B       C       D       E   F       G
0  df3_A0  df3_B0  df3_C0     NaN     NaN NaN     NaN
2  df3_A2  df3_B2  df3_C2     NaN     NaN NaN     NaN
5     NaN     NaN  df4_C2  df4_D2  df4_E2 NaN     NaN
6     NaN     NaN  df5_C6     NaN     NaN NaN     NaN
7     NaN     NaN  df5_C6     NaN     NaN NaN  df5_G6

In [13]:
df0 = get_df()
df0 = df0.dropna(axis=1, how='all')
# df0 = df0.dropna(axis=0, how='any')
df0

        A       B       C       D       E       G
0  df3_A0  df3_B0  df3_C0     NaN     NaN     NaN
1  df3_A1  df3_B1  df3_C1     NaN     NaN     NaN
2  df3_A2  df3_B2  df3_C2     NaN     NaN     NaN
3     NaN     NaN  df4_C4  df4_D4  df4_E4     NaN
4     NaN     NaN  df4_C3  df4_D3  df4_E3     NaN
5     NaN     NaN  df4_C2  df4_D2  df4_E2     NaN
6     NaN     NaN  df5_C6     NaN     NaN     NaN
7     NaN     NaN  df5_C6     NaN     NaN  df5_G6
8     NaN     NaN  df5_C7     NaN     NaN  df5_G7